//TODO: build inquirer prompt to grab the info from the user




//Requirements:
// inquirer prompt gathers all the info
// program generates a file and posts to the console
// an example svg generated by my program added to the 'examples' folder
// tests written using Jest
// a link to a walkthrough video demonstrating: 
//// --the inquirer prompt, and generated image
//// --a demonstration of the tests, and that all of them pass
// README file w/ link to the walkthrough video
// svg types: circle, rectangle, polygon
// image is 300x200