const inquirer = require('inquirer');
const fs = require('fs');
const {Circle, Square, Triangle} = require('./lib/shapes');

//TODO: build inquirer prompt to grab the info from the user



inquirer
        .prompt([
            {
                type: 'input',
                name: 'text',
                message: 'Enter the text for the logo. (max 3 characters)'
            },
            {
                type: 'input',
                name: 'textColor',
                message: 'What color should the text be? (enter a color word or hexcode)'
            },
            {
                type: 'list',
                name: 'shape',
                message: 'What shape should the logo background be? (choose from the following)',
                choices: ['Square', 'Circle', 'Triangle']
            },
            {
                type: 'input',
                name: 'shapeColor',
                message: 'What color should the shape be? (enter a color word or hexcode)'
            }
        ])
        .then((data) => {
            let textFinal = (data.text).toUpperCase();
            if (textFinal.length > 3) {
                textFinal = textFinal.substring(0,3)
            }
            let path = "./examples/" + textFinal + ".svg"

            if (data.shape == "Square") {
                const shape = new Square(data.shapeColor)
                fs.appendFile(path, `<svg 
                width="300" height="200"
                xmlns="http://www.w3.org/2000/svg" >
              
                <rect x="${shape.x}" y="${shape.y}" width="${shape.width}" height="${shape.height}" fill="${shape.fill}" />
              
                <text x="150" y="120" font-size="60" text-anchor="middle" fill="${data.textColor}">${textFinal}</text>
              
              </svg>`,
              (err) => err ? console.error(err) : console.log('File created successfully!'))
            } else if (data.shape == "Circle") {
                const shape = new Circle(data.shapeColor)
                fs.appendFile(path, `<svg 
                width="300" height="200"
                xmlns="http://www.w3.org/2000/svg" >
              
                <circle cx="${shape.cx}" cy="${shape.cy}" r="${shape.r}" fill="${shape.fill}" />
              
                <text x="150" y="120" font-size="60" text-anchor="middle" fill="${data.textColor}">${textFinal}</text>
              
              </svg>`,
              (err) => err ? console.error(err) : console.log('File created successfully!'))
            } else {
                const shape = new Triangle(data.shapeColor)
                fs.appendFile(path, `<svg 
                width="300" height="200"
                xmlns="http://www.w3.org/2000/svg" >
              
                <polygon points="${shape.points}" fill="${shape.fill}"/>
              
                <text x="150" y="165" font-size="60" text-anchor="middle" fill="${(data.textColor)}">${textFinal}</text>
              
              </svg>`,
              (err) => err ? console.error(err) : console.log('File created successfully!'))
            }
        })

//Requirements:
// program generates a file and posts to the console
// an example svg generated by my program added to the 'examples' folder
// tests written using Jest
// a link to a walkthrough video demonstrating: 
//// --the inquirer prompt, and generated image
//// --a demonstration of the tests, and that all of them pass
// README file w/ link to the walkthrough video